language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
before_install:
  - sudo apt-get update
  - sudo apt-get install snmp -y
  - sudo apt-get install snmp-mibs-downloader -y
  - sudo apt-get install libsnmp-dev -y
  - sudo apt-get install gcc python-dev -y
install:
  - pip install -r requirements.txt
script: py.test