language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
before_install:
  - apt-get update
  - apt-get -y install libsnmp-dev
install:
  - pip install -r requirements.txt
script: py.test